### PR TITLE
Add data description table for GESIS and LISS.

### PR DESCRIPTION
**Pull request by roecla**
[x] create the data description table
[] nice name for every variable
[] double check all columns
[] improve language

[x] add documentation of the data description table

### CODE REVIEW

**Comment by raholler** [comment]
nice name: we should have names for plots, I guess we need three names: a dutch, a German and an English name (?)

**Comment by roecla** [comment]
very good point. I hadn't thought about languages much yet. 
I think everything in the data set should be in English at the end of the data cleaning. 

The translation of variable names, category labels etc. into other languages is an interesting question. We could collect this in the table. However, if that's worth it or not depends on how much we automate at later stages where we could use that. 

If we decide to translation on demand, the question is whether `label` and especially `nice_name` really belong in the table.

**Comment by raholler** [comment]
where else should nice name be? -> need sth to make everything consistent

I think only everything that will be used in texts or plot/table labels needs to be translated, everything else can stay as is. So topic, subtopic and co can stay in english only I guess (?).

Categories and orders are missing from the table, but they are supposed to be in this csv file as well in the long run? (because that is not in the todo list above).

Did you double check whether you have everything from GESIS Corona Questionnaire as well ? Or do you want to make to separate tables?

If not additional column -> GESIS original name , LISS original name

**Comment by janosg** [comment]
Yes, the information in all languages should be in the same table! Otherwise we have some error prone duplication of information. There can be suffixes (_german, _dutch, ...) for labels, nice_names and so on. Only what is currently called "new_name" should not be translated. Topic and Subtopic might be used as titles, so there should also be a translation.

The most difficult and time consuming part is to translate the labels of categorical variables. 

I haven't thought much about text in the dashboard yet. But I will keep it all in yaml or json files, so someone could translate my English text to German and Dutch. Then we can provide all visualizations in the three relevant languages.

**Comment by roecla** [comment]
> where else should nice name be? -> need sth to make everything consistent

I don't understand what you mean with this. Do you mean where we are going to use `nice_name` in the dashboard? 

> I think only everything that will be used in texts or plot/table labels needs to be translated, everything else can stay as is. So topic, subtopic and co can stay in english only I guess (?).

I haven't added German and Dutch columns yet and would suggest we do this once the first version of the dashboard stands in English.

> Categories and orders are missing from the table, but they are supposed to be in this csv file as well in the long run? (because that is not in the todo list above).
 
I do have `categories_english` and `ordered` in the table. Can you check again?

> Did you double check whether you have everything from GESIS Corona Questionnaire as well ? Or do you want to make to separate tables?
> If not additional column -> GESIS original name , LISS original name

I did not double check but I built the table first from the GESIS questionnaire and then expanded it with the LISS questionnaire. There are a `gesis` and a `liss` column in the csv file. `gesis` is a boolean at the moment if the question is in the questionnaire. That will have to be filled once we get the dataset. For the `liss` column I added the questionnaire identifiers. I think double checking with the questionnaire is not necessary if you get the questionnaire starting next week. 

Since the categories might be in different languages or otherwise different between the translated categories and datasets, I added `gesis categories` and `liss categories` so that we can easily translate the value labels.

**Comment by raholler** [comment]
Nice! Sorry half of my questions were abundant as I did not see some of the columns...

The nice_names thing was because you suggested not to put it in the table, but I think it should be in the table.

**Comment by roecla** [comment]
OK. Then I will merge this and move the remaining tasks to clickup.

**Pull request merged**
